export const ErrorCodes = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  NO_CONNECTION: "NO_CONNECTION",
  NOT_CONNECTED: "NOT_CONNECTED",
  NO_CALENDARS_SELECTED: "NO_CALENDARS_SELECTED",
  SYNC_FAILED: "SYNC_FAILED",
  BAD_CANDIDATE_RANK: "BAD_CANDIDATE_RANK",
  MUST_HAVE_OWNER: "MUST_HAVE_OWNER",
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
  CONFLICT: "CONFLICT",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  BAD_REQUEST: "BAD_REQUEST",
  ACCESS_TOO_LOW: "ACCESS_TOO_LOW",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
